dbt:
  outputs:
    dev:
      account: ms36734.ap-southeast-2
      database: DEMO_DBT
      password: Smecnet121!
      role: dbt_DEV_ROLE
      schema: public
      threads: 200
      type: snowflake
      user: ggww128
      warehouse: dbt_DEV_WH
    staging:
      host: adb-143677883514282.2.azuredatabricks.net
      http_path: /sql/1.0/warehouses/b3ec78ec065481d2
      schema: default
      threads: 4
      token: dapi52880c9ebf01473a1c26e5f7f7a3b4eb
      type: databricks
  target: staging
